### ISSUE TITLE
Clicking outside the modal when on import or transcription page, resets all progress to that point

### ISSUE THREAD

**Issue by chloebrett** [patrickbrett/mlvet#101]
E.g. you are here:

<img width="1440" alt="Screen Shot 2022-05-28 at 3 20 42 pm" src="https://user-images.githubusercontent.com/6735055/170811359-0826449f-f16a-4238-a643-e359251aac9e.png">

You then click anywhere outside of the modal. You are returned to the home screen and have to start again (naming project, importing media, etc).

Should instead, either:

1. Show a pop up warning you that you will lose progress if you go back to the home screen, do you want to anyway?

or

2. Just not do anything, the user can click cancel / the X in the corner instead

**Comment by emmapainter** [comment]
This seems pretty standard for modal behaviour, probably needs a warning though.
