### ISSUE TITLE
Let user drag to resize video preview / transcription panes

### ISSUE THREAD

**Issue by chloebrett** [patrickbrett/mlvet#107]
This is more of a feature than a bug/issue, but would be super neat if we could choose how much of the screen we want taken up by the video preview and how much by the transcription, by dragging in the middle.

**Comment by rileykeane** [comment]
Moved to ClickUp since it's not an 'issue'

**Comment by rileykeane** [comment]
Moved to ClickUp since it's not an 'issue'
