### ISSUE TITLE
Mac: update first menu button (currently "Electron")

### ISSUE THREAD

**Issue by chloebrett** [patrickbrett/mlvet#118]
Should be MLVET ([or whatever we end up calling this](https://github.com/patrickbrett/mlvet/issues/117)) and the "about" button should give info about our app (version etc) rather than Electron version and logo

**Comment by jhea0008** [comment]
Issue has been resolved
<img width="351" alt="Screen Shot 2022-09-02 at 10 27 47" src="https://user-images.githubusercontent.com/69192205/188034172-02b80965-fbc2-43ad-a015-f126fba7cf7a.png">
