### ISSUE TITLE
Refactor: extract UI components

### ISSUE THREAD

**Issue by chloebrett** [patrickbrett/mlvet#119]
All UI components (in the format of styled\`...\`) should be separated from components with logic in them, and shared. Otherwise we keep reinventing the wheel doing things like this:

<img width="465" alt="Screen Shot 2022-05-28 at 3 59 35 pm" src="https://user-images.githubusercontent.com/6735055/170812364-c6fcddf3-812a-4d9f-9eca-5af905e4e985.png">

(this is in a logic component file)

**Comment by ghost** [comment]
@chloebrett , I have created [a branch for this](https://github.com/chloebrett/mlvet/tree/chore/extract-UI-components).

Buttons have been extracted but I have yet to extract styled components like custom stacks.

I have some thoughts below - if you could please have a read through.

I see your point that we are reinventing the wheel but I'm not sure it is worth extracting them. 
1. I don't think many people will think to check if these sorts of styled components have been defined somewhere else before using them. Hence, I don't think they'll get used often in the future. Having said that, componentising them elsewhere will clean up the existing code a bit.
2. While it is duplicate code, I'm not sure all the uses can be shared. Might want to change one but not other, etc.

Let me know what you think :)
