### ISSUE TITLE
Drag Feature - Word can't be released after drag starts

### ISSUE THREAD

**Issue by Irmy** [patrickbrett/mlvet#246]
I believe Hugh and Chloe are already aware of this - again just listing so team is aware  - see video below. 
Using drag via alt - word is never released - have to click out of app. 

https://user-images.githubusercontent.com/55219708/187619819-0a5bf943-2653-4db2-b9d8-6d2feca5bf43.mp4

**Comment by Mhudlark** [comment]
Dragging removed
