### ISSUE TITLE
App crashes if word is pasted at end of transcription and then Crtl + Z undo triggers error

### ISSUE THREAD

**Issue by Irmy** [patrickbrett/mlvet#252]
As above @chloebrett 
![image](https://user-images.githubusercontent.com/55219708/187661164-33364d80-5db2-449e-93a0-a9a08fb28b68.png)

https://user-images.githubusercontent.com/55219708/187661474-1df8a72a-d8b9-4db3-a1f1-4d71b4a638ba.mp4

**Comment by chloebrett** [comment]
Closed as resolved by #340
