### ISSUE TITLE
Undoing a delete selection will restore all deletions within the selection

### ISSUE THREAD

**Issue by itsMoxMox** [patrickbrett/mlvet#287]
Undo delete in a selection will even undo deletions that occurred prior to most recent delete operation.

Video for demo.

https://user-images.githubusercontent.com/55727741/190887207-843d2a55-f1fb-4b22-9773-662444bdf056.mp4

**Comment by chloebrett** [comment]
Same issue as #292 (I realise this one was first), resolved by #341
