### ISSUE TITLE
API vs Sockets for Python/Node interface

### ISSUE THREAD

**Issue by kateahyde** [patrickbrett/mlvet#29]
This is just to make the current discussion on using API endpoints vs sockets for getting the transcription output from Python to Node. Here are the main parts of the discussion that's already taken place so far on one of the PRs:

_Kate:_ Mutaz and I were discussing a potential alternative solution for the API I'm working on where the output is pushed to a file rather than returned directly..... I'm planning to do a GET endpoint which will return the transcription directly, however we were discussing the potential for the request to timeout if it's a large video file. We were contemplating a different approach where the initial call to the GET endpoint starts a thread that runs the transcription in the background and returns a 200 OK (or similar) immediately after starting the thread, and then the calling Node code will have to poll another endpoint for the status on the transcription and when it's complete it will have a reference to a file containing the output. This is a bit rough atm, and I was planning to flesh it out a bit more and look at if and how it would work once I have the basic GET fully implemented.

_Patrick:_ Sockets are a good solution for this use case! That way python can push the completed transcription instead of node having to poll

_Kate:_ True, good point! I can't remember exactly why we thought an API would be better but if it's not going to do what we need then a socket approach is defs worth looking into (and will hopefully be simpler than creating threads and trying to keep track of their status) :)

I'll look into sockets and update this issue once I've made some progress

**Comment by kateahyde** [comment]
Continuing the convo here @patrickbrett @Taz17 (although don't think there's too much more to say till I've had a chance to look into the socket option a bit more)

**Comment by chloebrett** [comment]
This is a good candidate for a design doc :)
