### ISSUE TITLE
Can't use enter/return to confirm project name

### ISSUE THREAD

**Issue by jhea0008** [patrickbrett/mlvet#47]
On the new project dialogue, when typing the project name, if enter/return is pressed, nothing happens. Instead it is required to press continue with the mouse. Keyboard key Enter/return should be able to be used as a replacement for pressing the continue button

**Comment by MutazAshhab** [comment]
check out this bad boy #49

**Comment by MutazAshhab** [comment]
Its in a different PR than #38 just because we want to separate concerns.

**Comment by emmapainter** [comment]
@Taz17 is this resolved?

**Comment by MutazAshhab** [comment]
@emmapainter no, we closed that PR in favor of using forms. I will probably reassess the use of event listeners over forms.
