### ISSUE TITLE
Deleting a project in the opening menu removes new project option

### ISSUE THREAD

**Issue by kateahyde** [patrickbrett/mlvet#77]
When you press the trash can on a project in the main menu it removes everything from the page not just the project you delete

**Comment by chloebrett** [comment]
Is this on develop? The delete project functionality isn’t even merged yet

**Comment by chloebrett** [comment]
See if it happens here #73

**Comment by kateahyde** [comment]
It's from what I've merged into my branch from develop, I haven't done anything with frontend on my branch so I'm confident it's not from anything I've done

**Comment by kateahyde** [comment]
I've had a look, the delete-project branch doesn't put the project on the main menu like it does in develop

**Comment by chloebrett** [comment]
What do you mean by main menu? Home screen?

**Comment by kateahyde** [comment]
Yep home screen sorry

**Comment by emmapainter** [comment]
@patrickbrett has this been fixed?
